services:
  bookcity_server:
    build: .
    image: bookcity
    container_name: bookcity_server
    ports:
      - "5000:5000"
    links:
      - mysql_server
    environment:
      MYSQL_HOST: mysql_server
      MYSQL_DB: bookstore
      MYSQL_USER: root
      MYSQL_PWD: Cjl202200202127==

  mysql_server:
    build: ./mysql
    image: mysql-bookcity
    container_name: mysql_server
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Cjl202200202127==
      MYSQL_DATABASE: bookstore



